# GitHub Sponsors - 台灣銀行不支援，暫時停用
# github: ['Sid-1996']

# 🌟 主要捐贈平台

# 愛發電 (Afdian) - 中國大陸用戶推薦
custom: ['https://afdian.com/a/sid-1996']

# Ko-fi - 國際用戶推薦
ko_fi: sid-1996

# PayPal 捐贈連結
custom: ['https://www.paypal.com/ncp/payment/GJS4D5VTSVWG4', 'https://www.paypal.com/ncp/payment/S5PTHJJVBC5VS']

# 綠界科技支付 (Taiwan) - 台灣用戶首選
custom: ['https://p.ecpay.com.tw/E0E3A']

# 🔄 未來可能啟用的平台

# Patreon (如果將來啟用)
# patreon: your-patreon-username

# Open Collective (如果將來啟用)
# open_collective: your-collective-name

# Buy Me a Coffee (台灣用戶可考慮)
# buy_me_a_coffee: your-username

# Tidelift (如果將來啟用)
# tidelift: your-package-name

# Community Bridge (如果將來啟用)
# community_bridge: your-project-name

# Liberapay (如果將來啟用)
# liberapay: your-username

# IssueHunt (如果將來啟用)
# issuehunt: your-username

# Otechie (如果將來啟用)
# otechie: your-username
